#!/bin/bash

#SBATCH --job-name=test_job
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=15
#SBATCH --cpus-per-task=1
#SBATCH --partition=mrcieu
#SBATCH --time=10:00:00
#SBATCH --mem=10000M

 #installation 
conda env create --file environment.yml
source activate ldsc

cd /xxxxx
./ldsc.py -h
./munge_sumstats.py -h

wget https://data.broadinstitute.org/alkesgroup/LDSCORE/w_hm3.snplist.bz2
bunzip2 w_hm3.snplist.bz2


./munge_sumstats.py \
--sumstats depression_102.txt \
--N 500199 \
--out dep_102 \
--merge-alleles w_hm3.snplist

./munge_sumstats.py \
--sumstats BMI.txt \
--out BMI \
--chunksize 500000 \
--merge-alleles w_hm3.snplist

./munge_sumstats.py \
--sumstats GlycA.txt \
--N 115078 \
--out GlycA \
--chunksize 500000 \
--merge-alleles w_hm3.snplist


./ldsc.py \
--rg BMI.sumstats.gz,dep_102.sumstats.gz,GlycA.sumstats.gz \
--ref-ld-chr eur_w_ld_chr/ \
--w-ld-chr eur_w_ld_chr/ \
--out bmi_dep_GlycA
